import { LanguageOption, PresetDialogue, ThemeConfig } from "./types";

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  {
    code: "ko",
    name: "Korean (한국어)",
    placeholderText: "안녕하세요. 만나서 반갑습니다.",
    placeholderRom: "Annyeonghaseyo. Mannaseo bangapseumnida.",
    placeholderTrans: "Ciao. Piacere di conoscerti.",
  },
  {
    code: "ja",
    name: "Japanese (日本語)",
    placeholderText: "こんにちは。お元気ですか？",
    placeholderRom: "Konnichiwa. O-genki desu ka?",
    placeholderTrans: "Ciao. Come stai?",
  },
  {
    code: "zh",
    name: "Chinese (中文)",
    placeholderText: "你好！很高兴认识你。",
    placeholderRom: "Nǐ hǎo! Hěn gāoxìng rènshí nǐ.",
    placeholderTrans: "Ciao! Molto felice di conoscerti.",
  },
  {
    code: "ar",
    name: "Arabic (العربية)",
    placeholderText: "مرحباً كيف حالك؟",
    placeholderRom: "Marhaban, kayfa haluk?",
    placeholderTrans: "Ciao, come stai?",
  },
  {
    code: "hi",
    name: "Hindi (हिन्दी)",
    placeholderText: "नमस्ते! आपसे मिलकर खुशी हुई।",
    placeholderRom: "Namaste! Aapse milkar khushi hui.",
    placeholderTrans: "Ciao! Felice di incontrarti.",
  },
  {
    code: "el",
    name: "Greek (Ελληνικά)",
    placeholderText: "Γεια σας! Τι κάνετε;",
    placeholderRom: "Gia sas! Ti kanete?",
    placeholderTrans: "Ciao! Come state?",
  },
  {
    code: "ru",
    name: "Russian (Русский)",
    placeholderText: "Привет! Как дела?",
    placeholderRom: "Privet! Kak dela?",
    placeholderTrans: "Ciao! Come va?",
  },
  {
    code: "es",
    name: "Spanish (Español)",
    placeholderText: "¡Hola! ¿Cómo estás?",
    placeholderRom: "(H-pronunciation is silent, speak softly)",
    placeholderTrans: "Ciao! Come stai?",
  },
  {
    code: "fr",
    name: "French (Français)",
    placeholderText: "Bonjour! Enchanté de vous rencontrer.",
    placeholderRom: "(R-sound is guttural, link syllables)",
    placeholderTrans: "Buongiorno! Piacere di incontrarvi.",
  },
  {
    code: "de",
    name: "German (Deutsch)",
    placeholderText: "Guten Tag! Wie geht es Ihnen?",
    placeholderRom: "(V-sounds like F, stress the first syllable)",
    placeholderTrans: "Buongiorno! Come sta?",
  },
  {
    code: "it",
    name: "Italian (Italiano)",
    placeholderText: "Buongiorno! Benvenuto nel nostro paese.",
    placeholderRom: "(Roll the R gently, sing-song timing)",
    placeholderTrans: "Good morning! Welcome to our country.",
  },
];

export const THEME_CONFIGS: ThemeConfig[] = [
  {
    id: "lavender_field",
    name: "Campi di Lavanda (Lilla)",
    bgGradient: "linear-gradient(135deg, #F3E5F5 0%, #E1BEE7 50%, #CE93D8 100%)",
    fontSans: "font-sans",
    emojiOverlay: "lavender",
    borderColor: "border-purple-300",
    textColor: "text-purple-900",
    accentColor: "bg-purple-600 text-white hover:bg-purple-700",
  },
  {
    id: "sakura_breeze",
    name: "Fiori di Ciliegio (Rosa)",
    bgGradient: "linear-gradient(135deg, #FFF0F5 0%, #FFD1DC 40%, #FFB7C5 100%)",
    fontSans: "font-sans",
    emojiOverlay: "sakura",
    borderColor: "border-pink-300",
    textColor: "text-pink-950",
    accentColor: "bg-pink-600 text-white hover:bg-pink-700",
  },
  {
    id: "matcha_green",
    name: "Tè Matcha (Verde Salvia)",
    bgGradient: "linear-gradient(135deg, #F1F8E9 0%, #DCEDC8 50%, #C5E1A5 100%)",
    fontSans: "font-sans",
    emojiOverlay: "matcha",
    borderColor: "border-emerald-300",
    textColor: "text-emerald-950",
    accentColor: "bg-emerald-700 text-white hover:bg-emerald-800",
  },
  {
    id: "sunset_warmth",
    name: "Tramonto Caldo (Fascia Sole)",
    bgGradient: "linear-gradient(135deg, #FFFDE7 0%, #FFE082 40%, #FFB74D 100%)",
    fontSans: "font-sans",
    emojiOverlay: "sunset",
    borderColor: "border-amber-300",
    textColor: "text-amber-950",
    accentColor: "bg-amber-600 text-white hover:bg-amber-700",
  },
  {
    id: "cosmic_sparkle",
    name: "Notte Cosmica (Dark)",
    bgGradient: "linear-gradient(135deg, #0D0E15 0%, #171B2F 50%, #22294C 100%)",
    fontSans: "font-mono",
    emojiOverlay: "cosmic",
    borderColor: "border-slate-800",
    textColor: "text-slate-100",
    accentColor: "bg-indigo-600 text-white hover:bg-indigo-700",
  },
  {
    id: "minimal_chalk",
    name: "Gesso e Lavagna (Chiaro)",
    bgGradient: "linear-gradient(135deg, #FAFAFA 0%, #F5F5F5 60%, #EEEEEE 100%)",
    fontSans: "font-sans",
    emojiOverlay: "minimal",
    borderColor: "border-gray-200",
    textColor: "text-gray-900",
    accentColor: "bg-gray-800 text-white hover:bg-gray-900",
  },
  {
    id: "charcoal_slate",
    name: "Ardesia scura (Pro)",
    bgGradient: "linear-gradient(135deg, #121214 0%, #1A1A1E 60%, #26262B 100%)",
    fontSans: "font-sans",
    emojiOverlay: "charcoal",
    borderColor: "border-zinc-800",
    textColor: "text-zinc-50",
    accentColor: "bg-zinc-700 text-white hover:bg-zinc-600",
  },
];

export const PRESET_DIALOGUES: PresetDialogue[] = [
  {
    id: "preset_korean_intro",
    title: "Presentarsi in Coreano",
    targetLanguage: "Coreano",
    baseLanguage: "Italiano",
    bubbles: [
      {
        id: "ko_1",
        text: "안녕하세요.",
        romanization: "Annyeonghaseyo.",
        translation: "Ciao / Buongiorno.",
        speaker: "A",
      },
      {
        id: "ko_2",
        text: "안녕하세요. 만나서 반갑습니다.",
        romanization: "Annyeonghaseyo. Mannaseo bangapseumnida.",
        translation: "Ciao. Piacere di conoscerti.",
        speaker: "B",
      },
      {
        id: "ko_3",
        text: "이름이 뭐예요?",
        romanization: "Ireumi mwoyeyo?",
        translation: "Come ti chiami?",
        speaker: "A",
      },
      {
        id: "ko_4",
        text: "저는 민수입니다.",
        romanization: "Jeoneun Minsu-imnida.",
        translation: "Mi chiamo Minsu.",
        speaker: "B",
      },
      {
        id: "ko_5",
        text: "만나서 반갑습니다. 저는 유나입니다.",
        romanization: "Mannaseo bangapseumnida. Jeoneun Yuna-imnida.",
        translation: "Piacere di conoscerti! Io sono Yuna.",
        speaker: "A",
      },
      {
        id: "ko_6",
        text: "저도 만나서 반갑습니다.",
        romanization: "Jeodo mannaseo bangapseumnida.",
        translation: "Piacere mio di conoscerti.",
        speaker: "B",
      },
    ],
  },
  {
    id: "preset_japanese_cafe",
    title: "Ordinare al Caffè (Giapponese)",
    targetLanguage: "Giapponese",
    baseLanguage: "Italiano",
    bubbles: [
      {
        id: "ja_1",
        text: "いらっしゃいませ！何にしますか？",
        romanization: "Irasshaimase! Nani ni shimasu ka?",
        translation: "Benvenuti! Cosa desiderate ordinare?",
        speaker: "A",
      },
      {
        id: "ja_2",
        text: "これ、コーヒーを二つお願いします。",
        romanization: "Kore, kōhī o futatsu onegai shimasu.",
        translation: "Per favore, vorrei due di questi caffè.",
        speaker: "B",
      },
      {
        id: "ja_3",
        text: "はい、かしこまりました。他には？",
        romanization: "Hai, kashikomarimashita. Hoka ni wa?",
        translation: "Certamente. Desidera altro?",
        speaker: "A",
      },
      {
        id: "ja_4",
        text: "いいえ、大丈夫です。いくらですか？",
        romanization: "Iie, daijōbu desu. Ikura desu ka?",
        translation: "No, va bene così. Quanto viene?",
        speaker: "B",
      },
      {
        id: "ja_5",
        text: "全部で八百円になります。",
        romanization: "Zenbu de happyaku-en ni narimasu.",
        translation: "In totale sono 800 yen.",
        speaker: "A",
      },
    ],
  },
  {
    id: "preset_chinese_asking",
    title: "Chiedere indicazioni (Cinese)",
    targetLanguage: "Cinese",
    baseLanguage: "Italiano",
    bubbles: [
      {
        id: "zh_1",
        text: "请问，地铁站在哪里？",
        romanization: "Qǐngwèn, dìtiězhàn zài nǎlǐ?",
        translation: "Scusi, dove si trova la stazione della metropolitana?",
        speaker: "A",
      },
      {
        id: "zh_2",
        text: "地铁站就在前面，往前走。 ",
        romanization: "Dìtiězhàn jiù zài qiánmiàn, wǎng qián zǒu.",
        translation: "La stazione è proprio qui davanti, continui dritto.",
        speaker: "B",
      },
      {
        id: "zh_3",
        text: "走多久能到呢？",
        romanization: "Zǒu duōjiǔ néng dào ne?",
        translation: "Quanto tempo ci vuole a piedi?",
        speaker: "A",
      },
      {
        id: "zh_4",
        text: "大概走五分钟就到了。",
        romanization: "Dàgài zǒu wǔ fēnzhōng jiù dào le.",
        translation: "Ci vogliono circa cinque minuti a piedi.",
        speaker: "B",
      },
      {
        id: "zh_5",
        text: "非常感谢！太好客了。",
        romanization: "Fēicháng gǎnxiè! Tài hàokè le.",
        translation: "Grazie mille! Sei stato gentilissimo.",
        speaker: "A",
      },
    ],
  },
];
